services:
  # --- GPU 0 Instance ---
  ollama-gpu0:
    image: ollama/ollama:latest
    container_name: ollama-gpu0
    environment:
      - OLLAMA_CONTEXT_LENGTH=262144
      - OLLAMA_MAX_LOADED_MODELS=0
      - OLLAMA_NUM_PARALLEL=0
    env_file:
      - .env
    volumes:
      - models:/root/.ollama
    networks:
      - llm-network
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [all]
              capabilities: [ gpu ]

  # --- GPU 1 Instance ---
  # ollama-gpu1:
  #   image: ollama/ollama:latest
  #   container_name: ollama-gpu1
  #   environment:
  #     - OLLAMA_CONTEXT_LENGTH=262144
  #     - OLLAMA_MAX_LOADED_MODELS=1
  #     - OLLAMA_NUM_PARALLEL=0
  #   env_file:
  #     - .env
  #   volumes:
  #     - models:/root/.ollama
  #   networks:
  #     - llm-network
  #   restart: unless-stopped
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             device_ids: [ '1' ]
  #             capabilities: [ gpu ]

volumes:
  models:

networks:
  llm-network:
    driver: bridge
